# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import school_pb2 as protos_dot_school__pb2


class SchoolServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateStudent = channel.unary_unary(
                '/school.SchoolService/CreateStudent',
                request_serializer=protos_dot_school__pb2.Student.SerializeToString,
                response_deserializer=protos_dot_school__pb2.Student.FromString,
                )
        self.GetStudent = channel.unary_unary(
                '/school.SchoolService/GetStudent',
                request_serializer=protos_dot_school__pb2.Id.SerializeToString,
                response_deserializer=protos_dot_school__pb2.Student.FromString,
                )
        self.ListStudents = channel.unary_unary(
                '/school.SchoolService/ListStudents',
                request_serializer=protos_dot_school__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_school__pb2.StudentList.FromString,
                )
        self.DeleteStudent = channel.unary_unary(
                '/school.SchoolService/DeleteStudent',
                request_serializer=protos_dot_school__pb2.Id.SerializeToString,
                response_deserializer=protos_dot_school__pb2.Empty.FromString,
                )
        self.CreateTeacher = channel.unary_unary(
                '/school.SchoolService/CreateTeacher',
                request_serializer=protos_dot_school__pb2.Teacher.SerializeToString,
                response_deserializer=protos_dot_school__pb2.Teacher.FromString,
                )
        self.ListTeachers = channel.unary_unary(
                '/school.SchoolService/ListTeachers',
                request_serializer=protos_dot_school__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_school__pb2.TeacherList.FromString,
                )
        self.CreateSubject = channel.unary_unary(
                '/school.SchoolService/CreateSubject',
                request_serializer=protos_dot_school__pb2.Subject.SerializeToString,
                response_deserializer=protos_dot_school__pb2.Subject.FromString,
                )
        self.ListSubjects = channel.unary_unary(
                '/school.SchoolService/ListSubjects',
                request_serializer=protos_dot_school__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_school__pb2.SubjectList.FromString,
                )
        self.CreateClass = channel.unary_unary(
                '/school.SchoolService/CreateClass',
                request_serializer=protos_dot_school__pb2.Class.SerializeToString,
                response_deserializer=protos_dot_school__pb2.Class.FromString,
                )
        self.ListClasses = channel.unary_unary(
                '/school.SchoolService/ListClasses',
                request_serializer=protos_dot_school__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_school__pb2.ClassList.FromString,
                )
        self.GetClassesByTeacher = channel.unary_unary(
                '/school.SchoolService/GetClassesByTeacher',
                request_serializer=protos_dot_school__pb2.Teacher.SerializeToString,
                response_deserializer=protos_dot_school__pb2.ClassList.FromString,
                )
        self.EnrollStudentInClass = channel.unary_unary(
                '/school.SchoolService/EnrollStudentInClass',
                request_serializer=protos_dot_school__pb2.EnrollRequest.SerializeToString,
                response_deserializer=protos_dot_school__pb2.Class.FromString,
                )


class SchoolServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateStudent(self, request, context):
        """Students
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStudent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStudents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteStudent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTeacher(self, request, context):
        """Teachers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTeachers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSubject(self, request, context):
        """Subjects
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSubjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateClass(self, request, context):
        """Classes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListClasses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClassesByTeacher(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnrollStudentInClass(self, request, context):
        """Enrollment: agora recebe EnrollRequest
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchoolServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateStudent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateStudent,
                    request_deserializer=protos_dot_school__pb2.Student.FromString,
                    response_serializer=protos_dot_school__pb2.Student.SerializeToString,
            ),
            'GetStudent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStudent,
                    request_deserializer=protos_dot_school__pb2.Id.FromString,
                    response_serializer=protos_dot_school__pb2.Student.SerializeToString,
            ),
            'ListStudents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStudents,
                    request_deserializer=protos_dot_school__pb2.Empty.FromString,
                    response_serializer=protos_dot_school__pb2.StudentList.SerializeToString,
            ),
            'DeleteStudent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteStudent,
                    request_deserializer=protos_dot_school__pb2.Id.FromString,
                    response_serializer=protos_dot_school__pb2.Empty.SerializeToString,
            ),
            'CreateTeacher': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTeacher,
                    request_deserializer=protos_dot_school__pb2.Teacher.FromString,
                    response_serializer=protos_dot_school__pb2.Teacher.SerializeToString,
            ),
            'ListTeachers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTeachers,
                    request_deserializer=protos_dot_school__pb2.Empty.FromString,
                    response_serializer=protos_dot_school__pb2.TeacherList.SerializeToString,
            ),
            'CreateSubject': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSubject,
                    request_deserializer=protos_dot_school__pb2.Subject.FromString,
                    response_serializer=protos_dot_school__pb2.Subject.SerializeToString,
            ),
            'ListSubjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSubjects,
                    request_deserializer=protos_dot_school__pb2.Empty.FromString,
                    response_serializer=protos_dot_school__pb2.SubjectList.SerializeToString,
            ),
            'CreateClass': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateClass,
                    request_deserializer=protos_dot_school__pb2.Class.FromString,
                    response_serializer=protos_dot_school__pb2.Class.SerializeToString,
            ),
            'ListClasses': grpc.unary_unary_rpc_method_handler(
                    servicer.ListClasses,
                    request_deserializer=protos_dot_school__pb2.Empty.FromString,
                    response_serializer=protos_dot_school__pb2.ClassList.SerializeToString,
            ),
            'GetClassesByTeacher': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClassesByTeacher,
                    request_deserializer=protos_dot_school__pb2.Teacher.FromString,
                    response_serializer=protos_dot_school__pb2.ClassList.SerializeToString,
            ),
            'EnrollStudentInClass': grpc.unary_unary_rpc_method_handler(
                    servicer.EnrollStudentInClass,
                    request_deserializer=protos_dot_school__pb2.EnrollRequest.FromString,
                    response_serializer=protos_dot_school__pb2.Class.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'school.SchoolService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SchoolService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateStudent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/school.SchoolService/CreateStudent',
            protos_dot_school__pb2.Student.SerializeToString,
            protos_dot_school__pb2.Student.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStudent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/school.SchoolService/GetStudent',
            protos_dot_school__pb2.Id.SerializeToString,
            protos_dot_school__pb2.Student.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListStudents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/school.SchoolService/ListStudents',
            protos_dot_school__pb2.Empty.SerializeToString,
            protos_dot_school__pb2.StudentList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteStudent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/school.SchoolService/DeleteStudent',
            protos_dot_school__pb2.Id.SerializeToString,
            protos_dot_school__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateTeacher(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/school.SchoolService/CreateTeacher',
            protos_dot_school__pb2.Teacher.SerializeToString,
            protos_dot_school__pb2.Teacher.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListTeachers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/school.SchoolService/ListTeachers',
            protos_dot_school__pb2.Empty.SerializeToString,
            protos_dot_school__pb2.TeacherList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateSubject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/school.SchoolService/CreateSubject',
            protos_dot_school__pb2.Subject.SerializeToString,
            protos_dot_school__pb2.Subject.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListSubjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/school.SchoolService/ListSubjects',
            protos_dot_school__pb2.Empty.SerializeToString,
            protos_dot_school__pb2.SubjectList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateClass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/school.SchoolService/CreateClass',
            protos_dot_school__pb2.Class.SerializeToString,
            protos_dot_school__pb2.Class.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListClasses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/school.SchoolService/ListClasses',
            protos_dot_school__pb2.Empty.SerializeToString,
            protos_dot_school__pb2.ClassList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetClassesByTeacher(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/school.SchoolService/GetClassesByTeacher',
            protos_dot_school__pb2.Teacher.SerializeToString,
            protos_dot_school__pb2.ClassList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EnrollStudentInClass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/school.SchoolService/EnrollStudentInClass',
            protos_dot_school__pb2.EnrollRequest.SerializeToString,
            protos_dot_school__pb2.Class.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
